version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 20
    groups:
      "Github actions dependencies":
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/StabilityAI.Grpc/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 20
    groups:
      "Dotnet dependencies":
        patterns:
          - "*"
