name: Publish nuget

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore
      working-directory: StabilityAI.Grpc
      run: dotnet restore
    - name: Build
      working-directory: StabilityAI.Grpc
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      working-directory: StabilityAI.Grpc
      run: dotnet pack --no-build --configuration Release
    - name: Publish
      working-directory: StabilityAI.Grpc
      run: dotnet nuget push StabilityAI.Grpc/bin/Release/StabilityAI.Grpc.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
